version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_employee
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: employee_db
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - employee-network

  app:
    build: .
    image: employee_app:latest
    container_name: employee-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/employee_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
    networks:
      - employee-network
    entrypoint: [ "./wait-for-it.sh", "db:5432", "--", "java", "-jar", "app.jar" ]

volumes:
  postgres_data:

networks:
  employee-network:
